export const client = {
  name: "Lawntech Lawn Care Ltd",
  tagline: "Professional Lawn Care in Salisbury — Quality You Can Trust",
  description: "Professional lawn care services in Salisbury and surrounding areas. Trusted local experts with 197 Google reviews.",
  category: "Lawn Care",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Salisbury",
  county: "",
  postcode: "",
  basedIn: "Salisbury",
  founderName: "Dean",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.8",
  reviewCount: "197",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Peter Bond", rating: 5, text: "Have used Lawntech for a number of years and thoroughly recommend. Always professional, knowledgeable and committed to delivering excellent service. My lawn, albeit relatively small, is now less hassle and worry to look after and receives admiring comments from neighbours.", date: "2 weeks ago" },
    { name: "Alexis Mitchel-Rowe", rating: 5, text: "Ive been using Lawntech since moving into this old house - and old garden! - since Sept 2022. Thanks to Rob,  and the team at Lawntech, we have a great lawn despite losing it nearly entirely during the drought last year that we had in the south of Wiltshire last year. It recovered completely dispute no rain or access to water for months!! A great company!", date: "2 weeks ago", badge: "Local Guide" },
    { name: "Peter Mercer", rating: 5, text: "I have with with Lawntech for around 18 months now, as the UK's largest independent Lawncare company, they have a vast knowledge and understanding of their field, and in my opinion there's know one better when it comes to Lawncare.  Being a family owned/run business, their customer service, attention to detail and all round professionalism is second to none and really does set them apart.  Both the owner Jim and his team are an absolute pleasure to deal with and they come with my highest recommendation.", date: "3 weeks ago" },
    { name: "Andy Layton", rating: 5, text: "Excellent service, with comprehensive report. 👍 …", date: "2 months ago" },
    { name: "L P", rating: 1, text: "We instructed Lawn Tech due to a leatherjacket problem. When the engineer visited, this was discussed and we were put onto a monthly service plan. It was not made clear at the time that the leatherjacket treatment was not included in this plan, and we continued paying monthly under that assumption. It was only several months later that we were told it could be added on, once we were already in contract.  During visits, garden furniture was moved without care, resulting in damage, and areas of the lawn appeared to have been over-fertilised, which was later confirmed by our gardener.  Overall, this was poor value for money and a disappointing service.", date: "3 months ago", badge: "Local Guide" },
    { name: "Michael Walker", rating: 2, text: "Used this company but found lawn was no better now than it was before treatment started Cancelled due to time spend and cost ( 5 mins work)   will nor recommend sorry ,,but thanks to john", date: "4 months ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Lawntech Lawn Care Ltd | Professional Lawn Care in Salisbury",
    description: "Professional lawn care in Salisbury. 4.8 stars on Google with 197 reviews. Quality workmanship guaranteed.",
  },
};
